### Products Index Test
get http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4Mzc2MDJ9.v2yR3fGPum6rhpX6UWl6adywlf-DNkM3DcIUqkpGnOo

### Product Show Test to get specific product by ID
get http://localhost:3000/products/9

### Product Create Test
post http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4Mzc2MDJ9.v2yR3fGPum6rhpX6UWl6adywlf-DNkM3DcIUqkpGnOo

{
"name" : "currentuserprod2",
"price": 100,
"description": "Mydescriptionhere",
"supplier_id": 2,
"url": "blablabla"
}

### Product Update Test
patch  http://localhost:3000/products/9.json
Content-Type: application/json

{
"name" : "dddd  ",
"price": 999,
"supplier_id": 2,
"description": "Mydescriptionhere"
}

### Product Delete Test
delete http://localhost:3000/products/4.json

### Supplier Create Test
post http://localhost:3000/suppliers.json
Content-Type: application/json

{
"name" : "Coca Cola ",
"email": "cc@test.com",
"phone_number": "777-777-7777"
}

### Users Create Test
post http://localhost:3000/users.json
Content-Type: application/json

{
"name" : "test users",
"email": "test@test.com",
"password": "password",
"password_confirmation": "password"
}

### Create Sessions Test
post http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "test@test.com",
"password": "password"
}


