json.id product.id
json.name product.name
json.price product.price
json.tax product.tax
json.total product.total
json.is_discounted? product.is_discounted?
json.description product.description
json.inventory product.inventory
json.supplier product.supplier
json.categories product.categories
json.images product.images
